---
services:
  tergite-redis:
    restart: unless-stopped
    image: redis:${REDIS_VERSION:-8.4.0}
    logging:
      driver: ${LOGGING_DRIVER}
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  mss:
    restart: unless-stopped
    depends_on:
      tergite-redis:
        condition: service_healthy
    image: "tergite/tergite-mss:${MSS_VERSION:-v0.4.0}"
    build:
      context: apps/tergite-mss
      dockerfile: Dockerfile
    logging:
      driver: ${LOGGING_DRIVER}
    ports:
      - "8002:${MSS_PORT:-80}"
    environment:
      - MSS_CONFIG_FILE=/code/mss-config.toml
      - PRIVATE_KEY_FILE=/code/private-mss-key.pem
    volumes:
      - ./mss-config.toml:/code/mss-config.toml:ro
      - ./private-mss-key.pem:/code/private-mss-key.pem:ro
      - ./bcc_certs:/code/bcc_certs:ro
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'wget -qO- --server-response --tries=1 --quiet http://mss:${MSS_PORT:-80}/devices/ 2>&1 | grep -q "HTTP/1.1 200" || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  dashboard:
    restart: unless-stopped
    depends_on:
      mss:
        condition: service_healthy
    image: "tergite/tergite-dashboard:${DASHBOARD_VERSION:-v0.5.0}"
    build:
      context: apps/tergite-dashboard
      dockerfile: Dockerfile
      additional_contexts:
        parent-folder: ./
      args:
        - VITE_API_BASE_URL=${MSS_URL}
        - MSS_CONFIG_FILE=./mss-config.toml
    logging:
      driver: ${LOGGING_DRIVER}
    ports:
      - "3000:80"
    env_file:
      - .env

  grafana-alloy:
    restart: unless-stopped
    image: grafana/alloy:${GRAFANA_ALLOY_VERSION:-v1.13.2}
    logging:
      driver: ${LOGGING_DRIVER}
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.data/alloy:/var/lib/alloy/data
    command: "--server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
